DPA-7829: Downtime reason classification by indicators
x-tensive/DPA.SignalsScripts pull request #22
Opened 2023-06-23 05:34 UTC by alanextar

2023-06-27 04:43 UTC, AnatolyKochnev requested changes

2023-06-27 14:03 UTC, alanextar commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +                result = result == null ? dtSegments : result.Intersection(dtSegments);
будет вот так
![image](https://github.com/x-tensive/DPA.SignalsScripts/assets/38909456/360197c6-2e47-46fe-8061-126340f0f189)

2023-07-04 05:32 UTC, AnatolyKochnev requested changes
Возможно, стоит еще Грознову показать

2023-07-04 13:45 UTC, alanextar commented
> Возможно, стоит еще Грознову показать

@groznov посмотри, пожалуйста, дополнительно PR

2023-07-06 03:56 UTC, AnatolyKochnev approved these changes

2023-08-17 07:30 UTC, BukinStanislav commented
По согласованию с Алексей Михайлов эту задачу и PR закрываем.
Все будущие улучшения/доработки будут в отдельных тикетах.

2023-08-17 07:30 UTC, merged

2023-10-04 22:57 UTC, groznov reviewed
Для единообразия рекомендовал бы, как в DPA-7910 использовать PeriodContext вместо DateTimeSegments

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +        public static readonly long[] WorkcenterIds = new long[] { 375157389 };
WorkCenterIds

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +        public static readonly long[] WorkcenterIds = new long[] { 375157389 };
Планируется, что пользователи будут доставать id из базы? Может по имени РЦ искать?

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +    public static class IndicatorClassifierSettings
В DPA-7910 настройки в отдельном файле. Предлагаю сделать так же

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +            { "Rapid traverse override Channel 1, %",  (val) => (double)val < 20.0 },
Странно, что в примере причина задаётся на русском, а имя индикатора - на английском; хотя сказано, что они должны быть в одной (системной) локали. Предлагаю остановиться на английском повсюду

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +        };
Странно, что в примере причина задаётся на русском, а имя индикатора - на английском; хотя сказано, что они должны быть в одной (системной) локали. Предлагаю остановиться на английском повсюду

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +        public DateTimeSegments Segments { get; set; }
Сеттеры не нужны

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +            }
Мне снова не очень нравится поиск причины по имени. Если в настройках мы указываем Id РЦ - может указывать и Id причины?
Но здесь я не настаиваю, можно и так оставить; только следует всегда помнить про локаль и про то, что наименования причин нельзя будет менять без смены скриптов

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +            }
Мне снова не очень нравится поиск причины по имени. Если в настройках мы указываем Id РЦ - может указывать и Id причины?
Но здесь я не настаиваю, можно и так оставить; только следует всегда помнить про локаль и про то, что наименования причин нельзя будет менять без смены скриптов

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +            foreach (var workcenterId in IndicatorClassifierSettings.WorkcenterIds) {
workCenterId

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +                        info.Record.EndDate - info.Record.StartDate > IndicatorClassifierSettings.IgnoredDowntimesPeriods))).ToList();
Здесь не гарантируется, что info.Record.EndDate != null - нужно добавить проверку после ||

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +            var workcenterId = downtimeInfo.Record.Equipment.Id;
workCenterId

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +        private void ClassifySegments(DowntimeInfo downtimeInfo)
Как и в DPA-7910 я бы передавал сюда уже модель, а не объект БД. Плюс снова наименования: лучше что-то типа sourceDowntimeInfo и destinationDowntimeInfo

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +                var values = indicatorContext.GetIndicatorData(indicator.Id, StartDate, EndDate);
Если я правильно понял - эти StartDate и EndDate берутся из рекорда. Но особенности нашей системы в том, что время индикаторов и рекордов могут незначительно расходиться (в любую сторону), даже если индикатор сменился ровно в момент начала рекорда. Соответственно, следует брать значения индикаторов с небольшим запасом относительно рекордов. Величину запаса можно уточнить у разработчиков драйверов; предполагаю, что 0.5 - 1 секунды бдет достаточно

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +        private void AddSourceReasonsExceptClassifiedToModel(DowntimeInfoModel model, DowntimeInfo downtimeInfo, DateTimeSegments classifiedDowntimeSegments)
Опять же, лучше бы здесь работать с моделями source and destination, без объектов БД

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +            }
Здесь что-то сложное. Насколько я понимаю, нужно так же, как в DPA-7910 в интервал от Start до End записать множество новых причин, а оставшееся пустое место заполнить с помощью старых причин. В DPA-7910 это сделано гораздо проще и понятнее

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +                downtimeInfoService.Update(downtimeInfo.Record.Id, downtimeInfoModel);
Так же, как и в DPA-7910, предлагаю перед отправкой модели упорядочить причины по времени, и при необходимости обнулить endDate у последней причины

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +                    }
Если пользователя нет - проставлять системного

2023-10-04 22:57 UTC, groznov commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierHandler.cs
> +                    classifiedDowntimeSegments.Add(reasonClassifiedSegment);
Не уверен, что Segments хорошо работает с несортированными отрезками.
Для первой причины - всё будет хорошо
Для второй причины - Exclude отработает, потом в classifiedDowntimeSegments добавятся новые отрезки. И после этого forEach в classifiedDowntimeSegments могут оказаться отрезки, неотсортированные по времени
И для третьей причины в этом случае Exclude может глюкануть.
Соответственно, после окончания внутреннего forEach я бы для надёжности вставил сортировку classifiedDowntimeSegments

2023-10-05 07:01 UTC, BukinStanislav commented on IndicatorDowntimeClassifier/IndicatorDowntimeClassifierCommonScript.cs
> +            { "Rapid traverse override Channel 1, %",  (val) => (double)val < 20.0 },
это как на заводе есть - так и в скрипте задаем
и по идее это должно быть в классе  IndicatorClassifierSettings,
чтоб можно было проще сконфигурировать