DPA-7911: Notify master when operator is missing in production state
x-tensive/DPA.SignalsScripts pull request #35
Opened 2023-08-08 15:20 UTC by alanextar

https://jira-xa.x-tensive.com/browse/DPA-7911

2023-08-09 12:41 UTC, BukinStanislav requested changes

2023-08-09 12:41 UTC, BukinStanislav commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionTrigger.cs
> +        private IEventSource generalEventSource;
назови просто eventSource - зачем нам длинные имена

2023-08-09 12:41 UTC, BukinStanislav commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionHandler.cs
> +                () => new Dictionary<string, string> { { "EquipmentName", workcenter.Name } },
параметр лучше WorkCenterName назвать
во всем новом коде стараемся WorkCenter вместо Equipment использовать

2023-08-09 12:41 UTC, BukinStanislav commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionConfig.cs
> +        public static readonly string MessageTemplateName = "ProductionStateMissingOperator";
в комментарии я бы привел пример сообщения с параметром (имя рабочего центра)
для полноты картины

2023-08-09 12:41 UTC, BukinStanislav commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionHandler.cs
> +            var timer = new Timer(MissingOperatorNotificationTimeout.TotalMilliseconds) { AutoReset = false };
вообще Timer диспосить надо

2023-08-09 12:41 UTC, BukinStanislav commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionHandler.cs
> +        public override Task SignalHandleAsync(Signals2ScriptEventArgs args)
Первый момент.
Если мы остановим хендлер и триггер, то таймер все равно отработает.
Столкнулся с похожей проблемой в скриптах ZF.
Никакие CancellationToken в хендлерах у нас пока что не предусмотрены (5.9).
Буквально сегодня в версию 6.0 добавил костыльную поддержку токенов,
но там еще тестировать надо.
Красивое решение с текущей архитектурой не получается.

Второй момент.
По логике триггер место для условий/событий.
У нас сейчас условие открытия смены проверяется в хендлере.
И на самом деле ничего сильно плохого в этом не вижу.
Однако если учитывать "первый" момент, то, кажется, можно убить двух зайцев:
- перенести таймер и проверку условия на открытия смены в триггер
в хендлере останется только отправка нотификейшена
- в триггере же сделать CancellationToken, проверять его в callback таймера, и по StopAsync - отменять и диспосить CancellationTokenSource.

В общем можно в эту сторону подумать.

2023-08-09 20:36 UTC, alanextar commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionHandler.cs
> +                () => new Dictionary<string, string> { { "EquipmentName", workcenter.Name } },
тут использовал EquipmentName, так как такой параметр установлен в шаблонах сообщения, но можно и WorkcenterName использовать

2023-08-10 06:46 UTC, alanextar commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionHandler.cs
> +            var timer = new Timer(MissingOperatorNotificationTimeout.TotalMilliseconds) { AutoReset = false };
Добавил диспозинг в колбэк

2023-08-10 08:33 UTC, BukinStanislav commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionHandler.cs
> +                () => new Dictionary<string, string> { { "EquipmentName", workcenter.Name } },
согласен, спорный момент
ну да ладно

2023-08-10 08:34 UTC, BukinStanislav commented on MissingOperatorInProductionNotifier/MissingOperatorInProductionHandler.cs
> +            var timer = new Timer(MissingOperatorNotificationTimeout.TotalMilliseconds) { AutoReset = false };
согласен
если есть контракт - надо диспосить :)

2023-08-10 08:36 UTC, BukinStanislav approved these changes

2023-08-10 08:36 UTC, merged